### ISSUE TITLE
The bot is not connected to a voice channel error

### ISSUE THREAD

**Issue by RVZWN** [Kakarot-2000/Discord-Bot#3]
I host my bot on repl.it I downloaded the files, it plays the song in my files, I see the title and when I click it there it is in an audio format, but the bot itself does not play it and tells me he isn t connected to a voice channel, help. I followed the steps from the other 2 issues but nothing worked, please help !!!!

**Comment by Kakarot-2000** [comment]
Hi @RVZWN ,
When I just checked now, it shows an error "discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice" in the console (not sure why this wasn't happening before). 
Installing the PyNaCl library fixed the issue for me. 
Please do a pip install from the console and see if it fixes the issue for you✌

**Comment by RVZWN** [comment]
@Kakarot-2000 I have the PyNaCl up to date (1.4.0) ... still can't find the issue, I uploaded the /bin folder from ffmpeg and it still does not work
![akaneproblem1](https://user-images.githubusercontent.com/89150847/129938341-d717cdc0-ae19-466e-97ec-14d08cfda2e2.jpg)
![bin](https://user-images.githubusercontent.com/89150847/129938368-d2bccc4a-66b2-4be5-a176-7bc85a2b944f.jpg)
![code](https://user-images.githubusercontent.com/89150847/129938372-8b909f23-14cf-4857-a968-6ea80aa120ba.jpg)

**Comment by RVZWN** [comment]
@Kakarot-2000 and also, in my console there is are no errors as far as I can see

**Comment by RVZWN** [comment]
@Kakarot-2000 and again, I am doing everything, coding, hosting, etc on repl.it, is a website

**Comment by RVZWN** [comment]
Oh yeah, and also @Kakarot-2000, when I'm making him join the channel and play, it does not really play the song but I can see that he recognises the song, it appears in the files as shown and I can play the song in the perl.it itself not on discord..
![wtffff](https://user-images.githubusercontent.com/89150847/129939270-3c7b5679-27fb-4a2a-bc87-f85e680416ba.jpg)
![wtfffff](https://user-images.githubusercontent.com/89150847/129939283-7cb6d2f8-e3e3-41e2-a1d8-1a31eeb369aa.jpg)

**Comment by RVZWN** [comment]
@Kakarot-2000 these are all my installed packages
![Uploading installedpacks.jpg…]()

**Comment by RVZWN** [comment]
@Kakarot-2000 these are the packs that I've installed 
![installedpacks](https://user-images.githubusercontent.com/89150847/129939823-250a9a89-f058-4f94-8143-58d0805c0d40.jpg)

**Comment by Kakarot-2000** [comment]
Hey @RVZWN , have you tried testing locally before deploying? If there were any errors specific to the code then it should show up when testing locally.

**Comment by RVZWN** [comment]
@Kakarot-2000 Yes, I tried.. and nothing seems to be wrong

**Comment by RVZWN** [comment]
@Kakarot-2000 I think I solved it, it takes a good while until the bot starts singing but I think I nailed it, I simply removed every other specification in that command, leaving it like this : 
voice_channel.play(discord.FFmpegPCMAudio(filename))

That fixed it, idk :))

**Comment by Kakarot-2000** [comment]
@RVZWN Glad to know that it got fixed. 
What part of the code did you remove for this? Was it from the play() method or somewhere else?

**Comment by PilotaSbiellato** [comment]
@RVZWN I tried to simplify the command as you did, but unfortunately it keep telling me it's not connected to the voice channel without printing any error
